import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const file = resolve(process.cwd(), 'index.html');
let html = readFileSync(file, 'utf8');

const home = `<main id="main" class="house-home house-home-x10">
  <section class="x10-hero" aria-labelledby="home-title">
    <div class="x10-noise" aria-hidden="true"></div>
    <div class="container x10-hero-grid">
      <div class="x10-hero-copy">
        <p class="x10-kicker"><span></span> THE HOUSE / PLAYER INTELLIGENCE</p>
        <h1 id="home-title">PLAY<br><em>SMARTER.</em></h1>
        <p class="x10-lede">Casino. Poker. Slots. Tipsters. One premium intelligence layer built to surface signal before noise.</p>
        <div class="x10-hero-actions"><a class="x10-btn x10-btn-primary" href="/casinos/">Explore the house <span>↗</span></a><a class="x10-btn x10-btn-ghost" href="/tips/">Open The Floor <span>→</span></a></div>
        <div class="x10-proof" aria-label="Platform principles"><span>Decision-first</span><i></i><span>Evidence-led</span><i></i><span>18+ responsible</span></div>
      </div>
      <div class="x10-hero-deck" aria-label="Explore The House">
        <a class="x10-deck-card x10-deck-operators" href="/casinos/"><span class="x10-card-index">01</span><span class="x10-card-label">OPERATORS</span><div class="x10-card-art x10-rings" aria-hidden="true"><i></i><i></i><i></i><b></b></div><div class="x10-card-bottom"><small>OPERATOR PASSPORTS</small><strong>Find the right house.</strong><span>Explore ↗</span></div></a>
        <a class="x10-deck-card x10-deck-tips" href="/tips/"><span class="x10-card-index">02</span><span class="x10-card-label">TIPS</span><div class="x10-card-art x10-chart" aria-hidden="true"><span></span><i></i><b>82%</b><small>EDGE</small></div><div class="x10-card-bottom"><small>THE FLOOR</small><strong>Track the signal.</strong><span>Open ↗</span></div></a>
        <a class="x10-deck-card x10-deck-ledger" href="/ledger/"><span class="x10-card-index">03</span><span class="x10-card-label">STORIES</span><div class="x10-card-art x10-editorial-art" aria-hidden="true"><span>THE</span><b>LEDGER</b><i></i></div><div class="x10-card-bottom"><small>EDITORIAL</small><strong>Read beyond the odds.</strong><span>Read ↗</span></div></a>
        <div class="x10-edge-meter" aria-label="Demo House edge score"><span>HOUSE EDGE</span><strong>82</strong><small>/100</small><div class="x10-edge-bars" aria-hidden="true">${Array.from({length:14},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div></div>
      </div>
    </div>
  </section>

  <section class="x10-pulse" aria-label="The Pulse"><div class="container x10-pulse-grid"><div class="x10-pulse-title"><span class="x10-live-dot"></span><div><b>THE PULSE</b><small>LIVE HOUSE SIGNAL</small></div></div><a href="/tips/"><small>FOOTBALL</small><b>CHE vs ARS</b><span>O2.5 <em>1.91</em></span></a><a href="/casinos/"><small>OPERATORS</small><b>Northstar</b><span>House score <em>9.4</em></span></a><a href="/slots/"><small>SLOT DROP</small><b>Neon Vault</b><span>Fresh <em>NEW</em></span></a><a href="/coin/"><small>HOUSE COIN</small><b>Weekly reward</b><span>Balance <em>2,840</em></span></a></div></section>

  <section class="x10-section x10-operators"><div class="container"><header class="x10-section-head"><div><span>01 / DISCOVER</span><h2>TOP OPERATORS</h2></div><p>Operator cards built as decision UI — score, strengths and context before the affiliate CTA.</p><a href="/casinos/">View all operators ↗</a></header><div class="x10-operator-grid"><a class="x10-op-card x10-op-feature" href="/casinos/stake-review/"><div class="x10-op-head"><span>#01 / EDITOR PICK</span><b>9.4</b></div><div class="x10-op-wordmark">NORTHSTAR</div><div class="x10-op-tags"><span>FAST PAYOUT</span><span>MOBILE FIRST</span><span>CRYPTO</span></div><div class="x10-op-data"><div><small>PAYOUT</small><strong>FAST</strong></div><div><small>KYC</small><strong>LIGHT</strong></div><div><small>MOBILE</small><strong>9.6</strong></div><div><small>CATALOGUE</small><strong>2.1K</strong></div></div><div class="x10-op-cta"><span>OPERATOR PASSPORT</span><b>OPEN ↗</b></div></a><a class="x10-op-card" href="/casinos/stake-review/"><div class="x10-op-head"><span>#02 / POKER PICK</span><b>8.9</b></div><div class="x10-op-wordmark x10-op-wordmark-small">ORBIT</div><p>Poker-led lobby with a clean mobile path and transparent onboarding.</p><div class="x10-op-cta"><span>BEST FOR POKER</span><b>OPEN ↗</b></div></a><a class="x10-op-card" href="/casinos/stake-review/"><div class="x10-op-head"><span>#03 / NEW SIGNAL</span><b>8.7</b></div><div class="x10-op-wordmark x10-op-wordmark-small">VELVET ACE</div><p>Slot-first discovery with modern catalogue organization.</p><div class="x10-op-cta"><span>BEST FOR SLOTS</span><b>OPEN ↗</b></div></a></div><div class="x10-intents"><span>FIND BY INTENT</span><a href="/casinos/">Fast payout</a><a href="/poker/">Poker</a><a href="/casinos/">Crypto</a><a href="/casinos/">High roller</a><a href="/casinos/">Mobile first</a></div></div></section>

  <section class="x10-section x10-floor"><div class="container"><header class="x10-section-head"><div><span>02 / PERFORMANCE</span><h2>THE FLOOR</h2></div><p>Tipster performance styled like a sports trading terminal: track record first, prediction second.</p><a href="/tips/">Enter The Floor ↗</a></header><div class="x10-floor-grid"><article class="x10-live-pick"><div class="x10-live-head"><span><i></i> LIVE PICK</span><time>21:00</time><b>PREMIER LEAGUE</b></div><div class="x10-fixture"><div><small>MATCH</small><strong>CHELSEA <em>VS</em> ARSENAL</strong></div><div class="x10-edge-ring"><span>82%</span><small>EDGE</small></div></div><div class="x10-market"><div><small>MARKET</small><strong>OVER 2.5</strong></div><div><small>ODDS</small><strong>1.91</strong></div><div><small>STAKE</small><strong>1.0U</strong></div></div><div class="x10-form-chart" aria-hidden="true"><span></span><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="x10-pick-footer"><a href="/tipsters/james-k/"><span class="x10-avatar">JK</span><div><small>TIPSTER</small><strong>JAMES K.</strong></div></a><div><small>30D ROI</small><strong>+18.4%</strong></div><div><small>WIN RATE</small><strong>64%</strong></div><a class="x10-text-link" href="/tipsters/james-k/">FULL RECORD ↗</a></div></article><aside class="x10-tipsters"><header><div><span>TOP TIPSTERS</span><small>30 DAY FORM</small></div><a href="/tips/">ALL ↗</a></header><a href="/tipsters/james-k/"><span>01</span><i>JK</i><div><strong>James K.</strong><small>Football · 126 picks</small></div><b>+18.4%</b></a><a href="/tips/"><span>02</span><i>AR</i><div><strong>Alex R.</strong><small>Football · 98 picks</small></div><b>+14.8%</b></a><a href="/tips/"><span>03</span><i>MT</i><div><strong>Mark T.</strong><small>Football · 144 picks</small></div><b>+12.1%</b></a><div class="x10-tipster-metrics"><span>ROI</span><span>YIELD</span><span>WIN RATE</span><span>STREAK</span></div></aside></div></div></section>

  <section class="x10-section x10-slots"><div class="container"><header class="x10-section-head"><div><span>03 / SLOT CULTURE</span><h2>SLOT DROPS</h2></div><p>High-impact visual discovery for new drops, mechanics and providers — built to feel collectible, not catalogued.</p><a href="/slots/">Open Slot Floor ↗</a></header><div class="x10-slot-grid"><a class="x10-slot x10-slot-lead" href="/slots/neon-vault/"><span class="x10-slot-no">01 / FEATURED</span><div class="x10-vault-art" aria-hidden="true"><i></i><i></i><i></i><b>NV</b></div><div class="x10-slot-copy"><small>HOUSE STUDIO</small><strong>NEON<br>VAULT</strong><span>EXPLORE DROP ↗</span></div></a><a class="x10-slot x10-slot-orange" href="/slots/black-diamond/"><span class="x10-slot-no">02</span><div class="x10-diamond" aria-hidden="true"></div><div class="x10-slot-copy"><small>JACKPOT / TRENDING</small><strong>BLACK<br>DIAMOND</strong><span>OPEN ↗</span></div></a><a class="x10-slot x10-slot-moon" href="/slots/after-hours/"><span class="x10-slot-no">03</span><div class="x10-moon" aria-hidden="true"></div><div class="x10-slot-copy"><small>MEGAWAYS / FEATURED</small><strong>AFTER<br>HOURS</strong><span>OPEN ↗</span></div></a><a class="x10-slot x10-slot-zero" href="/slots/zero-hour/"><span class="x10-slot-no">04</span><div class="x10-zero" aria-hidden="true">0</div><div class="x10-slot-copy"><small>NEW / HIGH RTP</small><strong>ZERO<br>HOUR</strong><span>OPEN ↗</span></div></a></div></div></section>

  <section class="x10-section x10-utility"><div class="container x10-utility-grid"><div class="x10-coin-panel"><div class="x10-coin-copy"><span>04 / HOUSE COIN</span><h2>REWARD<br>THE SIGNAL.</h2><p>A loyalty layer designed around useful actions, transparent rewards and future Telegram-native journeys.</p><a class="x10-btn x10-btn-primary" href="/coin/">Open wallet ↗</a></div><div class="x10-coin-visual" aria-hidden="true"><div><span>H</span></div><b>2,840</b><small>DEMO BALANCE</small></div></div><div class="x10-notify-panel"><div class="x10-panel-title"><span>NOTIFICATIONS</span><a href="/notifications/">VIEW ALL ↗</a></div><a href="/notifications/"><i>TIP</i><div><strong>New pick is live</strong><small>James K. · Football</small></div><time>2m</time></a><a href="/notifications/"><i>HC</i><div><strong>Weekly reward ready</strong><small>+240 House Coin</small></div><time>1h</time></a><a href="/notifications/"><i>NEW</i><div><strong>Operator Passport</strong><small>Fresh review available</small></div><time>5h</time></a></div></div></section>

  <section class="x10-section x10-ledger"><div class="container"><header class="x10-section-head"><div><span>05 / EDITORIAL</span><h2>THE LEDGER</h2></div><p>Premium editorial with the rhythm of a modern culture magazine — not a WordPress sidebar archive.</p><a href="/ledger/">Read The Ledger ↗</a></header><div class="x10-ledger-grid"><a class="x10-story-lead" href="/ledger/poker-moment/"><div class="x10-story-art"><span>THE CULTURE ISSUE</span><strong>POKER<br>IS BACK.</strong><i>01</i></div><div class="x10-story-copy"><small>POKER / 8 MIN READ</small><h3>Why poker is having another moment</h3><p>Product, culture and community signals behind the renewed attention.</p><b>READ STORY ↗</b></div></a><div class="x10-story-side"><a href="/ledger/casino-choice/"><span>GUIDE / 6 MIN</span><h3>How to compare casino offers without the noise</h3><p>What matters before the headline bonus.</p><b>READ ↗</b></a><a href="/ledger/tipster-proof/"><span>TIPSTERS / 7 MIN</span><h3>What a transparent tipster record should show</h3><p>ROI is only useful when the record underneath is visible.</p><b>READ ↗</b></a></div></div></div></section>

  <section class="x10-close"><div class="container"><span>THE HOUSE / 2026</span><h2>LESS NOISE.<br><em>MORE SIGNAL.</em></h2><div><a class="x10-btn x10-btn-primary" href="/casinos/">Explore The House ↗</a><p>Casino · Poker · Slots · Tipsters · Editorial</p></div></div></section>
</main>`;

const cssTag = '<link rel="stylesheet" href="/src/styles/home-v2.css">';
if (!html.includes(cssTag)) html = html.replace('</head>', `${cssTag}</head>`);
html = html.replace(/<main id="main">[\s\S]*?<\/main>/, home);
writeFileSync(file, html);
console.log('Enhanced Home X10.');
